[nfs]
172.31.93.55 ansible_ssh_user='ec2-user'

[webservers]
172.31.82.90 ansible_ssh_user='ec2-user'
172.31.81.33 ansible_ssh_user='ec2-user'

[db]
172.31.81.212 ansible_ssh_user='ec2-user' 

[lb]
172.31.81.49 ansible_ssh_user='ubuntu'